version: '3.3'

services:
    restreamer:
        image: sitetune/multiplestream:latest
        networks:
            - backend
        ports:
            - "1935:1935"
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
networks:
    backend: