version: '3.3'

services:
    restreamer:
        image: marcosjunqueira/sitetune-multiplestream:0.0.1
        networks:
            - backend
        ports:
            - "1935:1935"
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
networks:
    backend: